# Generated by Django 2.2.10 on 2020-09-09 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('employee_id', models.CharField(max_length=30, null=True, unique=True)),
                ('student_id', models.CharField(max_length=30, null=True, unique=True)),
                ('image', models.FileField(null=True, upload_to='images/%Y/%m/%d/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=60, null=True)),
                ('phone', models.CharField(default='', max_length=60, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('date_of_birth', models.CharField(default='', max_length=60, null=True)),
                ('blood_group', models.CharField(default='', max_length=60, null=True)),
                ('gender', models.CharField(default='', max_length=60, null=True)),
                ('religion', models.CharField(default='', max_length=60, null=True)),
                ('initial', models.CharField(default='', max_length=60, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='images/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.CharField(max_length=60, null=True)),
                ('blood_group', models.CharField(max_length=60, null=True)),
                ('gender', models.CharField(max_length=60, null=True)),
                ('department', models.CharField(max_length=60, null=True)),
                ('religion', models.CharField(max_length=60, null=True)),
                ('image', models.FileField(null=True, upload_to='images/%Y/%m/%d/')),
                ('update_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
