# Generated by Django 2.2.10 on 2020-09-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
    ]
